#! /bin/csh

# Copyright 1992 Digital Equipment Corporation
# All Rights Reserved

#set life = ~vanroy/LifePackage/src/wild_life
set argv1 = ` echo *.lf`

foreach i ($argv1)
	(echo 'load("' $i:r.lf '")?' | noblank ;echo "" ; \
	cat $i:r.in  ; echo "halt?") | \
	../wild_life | \
	egrep -v '(Wild_Life|customizing|Copyright|Default|Garbage|Exiting|Peter)' > $i:r.out
	diff $i:r.out $i:r.ref > $i:r.diff
	echo -n `ls -l $i:r.diff`
	echo ""
end
